/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50720
 Source Host           : localhost:3306
 Source Schema         : test

 Target Server Type    : MySQL
 Target Server Version : 50720
 File Encoding         : 65001

 Date: 07/11/2018 19:01:55
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for agent
-- ----------------------------
DROP TABLE IF EXISTS `agent`;
CREATE TABLE `agent`  (
  `job_number` int(11) NULL DEFAULT NULL,
  `department` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `region` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `idcard` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `company_rankings` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `department_rankings` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `region_rankings` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `distance_first_company` double NULL DEFAULT NULL,
  `distance_first_department` double NULL DEFAULT NULL,
  `distance_first_region` double NULL DEFAULT NULL,
  `participate` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of agent
-- ----------------------------
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (123, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '99', NULL, NULL, NULL, 109, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '99', NULL, NULL, NULL, 109, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '99', NULL, NULL, NULL, 109, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '123', '', '99', NULL, NULL, NULL, 109, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '12', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '456', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '123', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, '12312', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12312', '3123', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '1231', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (21, '', NULL, '', '', NULL, NULL, NULL, NULL, 12, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '123', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '12', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, 123, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '1', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', '3', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `agent` VALUES (NULL, '', NULL, '', '', NULL, NULL, '2', NULL, NULL, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
